// Liste des villes espagnoles principales
export const villesEspagne: string[] = [
  "Madrid",
  "Barcelone",
  "Valence",
  "Séville",
  "Saragosse",
  "Malaga",
  "Murcie",
  "Palma de Majorque",
  "Las Palmas de Gran Canaria",
  "Bilbao",
  "Alicante",
  "Cordoue",
  "Valladolid",
  "Vigo",
  "Gijón",
  "L'Hospitalet de Llobregat",
  "La Corogne",
  "Grenade",
  "Vitoria-Gasteiz",
  "Elche",
  "Santa Cruz de Tenerife",
  "Oviedo",
  "Badalona",
  "Cartagena",
  "Terrassa",
  "Jerez de la Frontera",
  "Sabadell",
  "Móstoles",
  "Alcalá de Henares",
  "Pamplona",
  "Fuenlabrada",
  "Almería",
  "Leganés",
  "Santander",
  "Castellón de la Plana",
  "Burgos",
  "Albacete",
  "Getafe",
  "Salamanca",
  "Huelva",
  "Logroño",
  "Badajoz",
  "San Sebastián",
  "Lérida",
  "Marbella",
  "León",
  "Cádiz",
  "Tarragone",
  "Dos Hermanas",
  "Mataró",
  "Santa Coloma de Gramenet",
  "Jaén",
  "Ourense",
  "Alcorcón",
  "Reus",
  "Torrelavega",
  "Algeciras",
  "Cáceres",
  "Lugo",
  "Coslada",
  "Talavera de la Reina",
  "El Puerto de Santa María",
  "Melilla",
  "Pontevedra",
  "Ciudad Real",
  "Gandia",
  "Ferrol",
  "Ceuta",
  "Torrevieja",
  "Ávila",
  "Segovia",
  "Guadalajara",
  "Cuenca",
  "Soria",
  "Teruel",
  "Huesca",
  "Zamora",
  "Palencia",
  "Autre"
]
