// Liste des villes canadiennes principales
export const villesCanada: string[] = [
  "Toronto",
  "Montréal",
  "Calgary",
  "Ottawa",
  "Edmonton",
  "Winnipeg",
  "Vancouver",
  "Québec",
  "Hamilton",
  "Kitchener",
  "London",
  "Victoria",
  "Halifax",
  "Oshawa",
  "Windsor",
  "Saskatoon",
  "Regina",
  "Sherbrooke",
  "Barrie",
  "Kelowna",
  "Abbotsford",
  "Sudbury",
  "Kingston",
  "Saguenay",
  "Trois-Rivières",
  "Guelph",
  "Cambridge",
  "Whitby",
  "Gatineau",
  "Waterloo",
  "Saint Catharines",
  "Terrebonne",
  "Laval",
  "Markham",
  "Burlington",
  "Richmond",
  "Richmond Hill",
  "Vaughan",
  "Oakville",
  "Ajax",
  "Mississauga",
  "Brampton",
  "Surrey",
  "Burnaby",
  "Coquitlam",
  "Langley",
  "Delta",
  "North Vancouver",
  "West Vancouver",
  "New Westminster",
  "Port Coquitlam",
  "Maple Ridge",
  "White Rock",
  "Chilliwack",
  "Kamloops",
  "Nanaimo",
  "Prince George",
  "Vernon",
  "Penticton",
  "Courtenay",
  "Campbell River",
  "Duncan",
  "Port Alberni",
  "Powell River",
  "Williams Lake",
  "Quesnel",
  "Fort St. John",
  "Dawson Creek",
  "Prince Rupert",
  "Terrace",
  "Smithers",
  "Hazelton",
  "Burns Lake",
  "Houston",
  "Vanderhoof",
  "Fraser Lake",
  "Fort Nelson",
  "Tumbler Ridge",
  "Chetwynd",
  "Hudson's Hope",
  "Taylor",
  "Autre"
]
