// Liste des villes italiennes principales
export const villesItalie: string[] = [
  "Rome",
  "Milan",
  "Naples",
  "Turin",
  "Palerme",
  "Gênes",
  "Bologne",
  "Florence",
  "Bari",
  "Catane",
  "Venise",
  "Vérone",
  "Messine",
  "Padoue",
  "Trieste",
  "Brescia",
  "Parme",
  "Prato",
  "Modène",
  "Reggio de Calabre",
  "Reggio d'Émilie",
  "Perugia",
  "Livourne",
  "Ravenne",
  "Cagliari",
  "Foggia",
  "Rimini",
  "Salerne",
  "Ferrare",
  "Sassari",
  "Monza",
  "Syracuse",
  "Pescara",
  "Bergame",
  "Forlì",
  "Trente",
  "Vicence",
  "Terni",
  "Bolzano",
  "Novare",
  "Piacenza",
  "Ancône",
  "Andria",
  "Arezzo",
  "Udine",
  "Cesena",
  "Lecce",
  "Pesaro",
  "La Spezia",
  "Brindisi",
  "Pise",
  "Sienne",
  "Barletta",
  "Pistoia",
  "Guidonia Montecelio",
  "Carrare",
  "Comacchio",
  "Imola",
  "Grosseto",
  "Fiumicino",
  "Vigevano",
  "Caltanissetta",
  "Viterbe",
  "Vittoria",
  "Crotone",
  "Pavia",
  "Catanzaro",
  "Massa",
  "Casoria",
  "Cosenza",
  "Asti",
  "Raguse",
  "Trapani",
  "Gela",
  "Cinisello Balsamo",
  "San Severo",
  "Varese",
  "Cremona",
  "Frosinone",
  "Latina",
  "Biella",
  "Autre"
]
