// Liste des villes américaines principales
export const villesEtatsUnis: string[] = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Austin",
  "Jacksonville",
  "Fort Worth",
  "Columbus",
  "Charlotte",
  "San Francisco",
  "Indianapolis",
  "Seattle",
  "Denver",
  "Washington",
  "Boston",
  "El Paso",
  "Nashville",
  "Detroit",
  "Oklahoma City",
  "Portland",
  "Las Vegas",
  "Memphis",
  "Louisville",
  "Baltimore",
  "Milwaukee",
  "Albuquerque",
  "Tucson",
  "Fresno",
  "Sacramento",
  "Mesa",
  "Kansas City",
  "Atlanta",
  "Long Beach",
  "Colorado Springs",
  "Raleigh",
  "Miami",
  "Virginia Beach",
  "Omaha",
  "Oakland",
  "Minneapolis",
  "Tulsa",
  "Arlington",
  "Tampa",
  "New Orleans",
  "Wichita",
  "Cleveland",
  "Bakersfield",
  "Aurora",
  "Anaheim",
  "Honolulu",
  "Santa Ana",
  "Corpus Christi",
  "Riverside",
  "Lexington",
  "Stockton",
  "Henderson",
  "Saint Paul",
  "St. Louis",
  "Milwaukee",
  "Baltimore",
  "Yonkers",
  "Spokane",
  "Glendale",
  "Des Moines",
  "Reno",
  "Modesto",
  "Santa Clarita",
  "Birmingham",
  "Salt Lake City",
  "Rochester",
  "Grand Rapids",
  "Huntsville",
  "Columbus",
  "Madison",
  "Fort Wayne",
  "Worcester",
  "Richmond",
  "Cedar Rapids",
  "New Haven",
  "Lakeland",
  "Providence",
  "Chandler",
  "Buffalo",
  "Durham",
  "Chula Vista",
  "Toledo",
  "Fort Lauderdale",
  "Shreveport",
  "Fremont",
  "Montgomery",
  "Scottsdale",
  "Augusta",
  "Lubbock",
  "Chesapeake",
  "Mobile",
  "Des Moines",
  "Grand Prairie",
  "Richmond",
  "Yonkers",
  "Spokane",
  "Glendale",
  "Baton Rouge",
  "Huntsville",
  "Reno",
  "Santa Clarita",
  "Birmingham",
  "Salt Lake City",
  "Autre"
]
